import { collectAllDataSourceRows, isFullPage } from '@notionhq/client'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { normalizeMember, type Member } from '../../src/lib/notion.ts'
import { connectToDataSource } from './notion-connection.ts'

const OUTPUT_PATH = fileURLToPath(new URL('../../src/content/members.generated.ts', import.meta.url))
const PHOTOS_DIR = fileURLToPath(new URL('../../public/members/', import.meta.url))

const EXTENSION_BY_CONTENT_TYPE: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
}

/**
 * Downloads a member's photo and self-hosts it under public/members/, named by content hash.
 * Notion-uploaded files are served from temporary signed URLs that expire (~1hr) — since we bake
 * this URL into a static file, we can never store Notion's own link directly. Hashing the bytes
 * means an unchanged photo keeps the same local URL (cacheable) and a changed one gets a new one
 * automatically. Returns '' on any failure so one bad photo doesn't block the rest of the roster.
 */
async function downloadPhoto(url: string, memberId: string): Promise<string> {
  try {
    const response = await fetch(url)
    if (!response.ok) throw new Error(`HTTP ${response.status}`)

    const contentType = response.headers.get('content-type')?.split(';')[0]?.trim()
    const extension = contentType ? EXTENSION_BY_CONTENT_TYPE[contentType] : undefined
    if (!extension) throw new Error(`Unsupported content type: ${contentType ?? 'unknown'}`)

    const bytes = new Uint8Array(await response.arrayBuffer())
    const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8)
    const filename = `${memberId}-${hash}.${extension}`

    mkdirSync(PHOTOS_DIR, { recursive: true })
    writeFileSync(join(PHOTOS_DIR, filename), bytes)
    return `/members/${filename}`
  } catch (error) {
    console.warn(`[notion] could not download photo for ${memberId}:`, error instanceof Error ? error.message : error)
    return ''
  }
}

/** Downloads every member's photo and removes any previously-downloaded files that are no longer used. */
async function resolvePhotos(members: Member[]): Promise<Member[]> {
  const resolved = await Promise.all(
    members.map(async (member) => ({
      ...member,
      photo: member.photo ? await downloadPhoto(member.photo, member.id) : '',
    })),
  )

  const keep = new Set(resolved.map((member) => member.photo.split('/').pop()).filter(Boolean))
  if (existsSync(PHOTOS_DIR)) {
    for (const file of readdirSync(PHOTOS_DIR)) {
      if (!keep.has(file)) rmSync(join(PHOTOS_DIR, file))
    }
  }

  return resolved
}

/** Fetches the roster from Notion, downloads photos, and (re)writes the generated content file. Returns the row count, and whether the file's contents actually changed. */
export async function fetchAndWriteMembers(): Promise<{ count: number; changed: boolean }> {
  const { notion, dataSourceId } = await connectToDataSource()

  const rows = await collectAllDataSourceRows(notion, { data_source_id: dataSourceId })
  const members = await resolvePhotos(
    rows
      .filter(isFullPage)
      .map(normalizeMember)
      .sort((a, b) => a.name.localeCompare(b.name)),
  )

  const output = `// Auto-generated by scripts/fetch-members.ts — do not edit by hand.
import type { Member } from '../lib/notion.ts'

export const members: Member[] = ${JSON.stringify(members, null, 2)}
`

  const previous = existsSync(OUTPUT_PATH) ? readFileSync(OUTPUT_PATH, 'utf8') : null
  const changed = previous !== output
  if (changed) {
    writeFileSync(OUTPUT_PATH, output)
  }

  return { count: members.length, changed }
}
