import { Client, collectAllDataSourceRows, isFullDatabase, isFullPage } from '@notionhq/client'
import { writeFileSync } from 'node:fs'
import { normalizeMember } from '../src/lib/notion.ts'

function requireEnv(name: string): string {
  const value = process.env[name]
  if (!value) {
    console.error(`Missing required environment variable: ${name}`)
    process.exit(1)
  }
  return value
}

const NOTION_TOKEN = requireEnv('NOTION_TOKEN')
const NOTION_DB_ID = requireEnv('NOTION_DB_ID')

async function main() {
  const notion = new Client({ auth: NOTION_TOKEN, notionVersion: '2025-09-03' })

  const database = await notion.databases.retrieve({ database_id: NOTION_DB_ID })
  if (!isFullDatabase(database)) {
    throw new Error('Notion returned a partial database response — check the integration has full access.')
  }

  const dataSourceId = database.data_sources[0]?.id
  if (!dataSourceId) {
    throw new Error('The Notion database has no data sources.')
  }

  const rows = await collectAllDataSourceRows(notion, { data_source_id: dataSourceId })
  const members = rows
    .filter(isFullPage)
    .map(normalizeMember)
    .sort((a, b) => a.name.localeCompare(b.name))

  const output = `// Auto-generated by scripts/fetch-members.ts — do not edit by hand.
import type { Member } from '../lib/notion.ts'

export const members: Member[] = ${JSON.stringify(members, null, 2)}
`

  writeFileSync(new URL('../src/content/members.generated.ts', import.meta.url), output)
  console.log(`Wrote ${members.length} member(s) to src/content/members.generated.ts`)
}

main().catch((error: unknown) => {
  console.error('Failed to fetch members from Notion:', error)
  process.exit(1)
})
